#!/bin/sh

xmodmap $XDG_CONFIG_HOME/keymaps/.Xmodmap

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

dbus-update-activation-environment --all
exec qtile start
