[colors.bright]
black = "#595959"
blue = "#79a8ff"
cyan = "#4ae2f0"
green = "#70b900"
magenta = "#f78fe7"
red = "#ff6b55"
white = "#ffffff"
yellow = "#ffa00f"

[colors.normal]
black = "#000000"
blue = "#79a8ff"
cyan = "#76afbf"
green = "#70b900"
magenta = "#f78fe7"
red = "#ff6b55"
white = "#bfbfbf"
yellow = "#cabf00"

[colors.primary]
background = "#1d2021"
foreground = "#ffffff"
